spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5432/shop_Phone
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

keycloak:
  server-url: http://localhost:8080
  realm: phone-store
  client-id: phone-store-client
  client-secret: 4itExXPxTCWWIBfccM55G54fpI4wdhzkZnh9lNcHqLiWch1a1AbYDSZbnEKV1m3Ux4FMngvqMqHrp6URRVxHUa

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"